#!/usr/bin/env python3
"""Write version_info.txt from version.py for PyInstaller Windows resources."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION_PY = ROOT / "version.py"
VERSION_INFO = ROOT / "version_info.txt"

_TEMPLATE = """# UTF-8 version resource for Windows EXE (PyInstaller) — generated by tools/sync_version_info.py
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, 0),
    prodvers=({major}, {minor}, {patch}, 0),
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable("040904B0", [
        StringStruct("CompanyName", "Bunbob41"),
        StringStruct("FileDescription", "Serial Link — Ethernet ↔ serial"),
        StringStruct("FileVersion", "{semver}"),
        StringStruct("InternalName", "serial-link"),
        StringStruct("OriginalFilename", "serial-link.exe"),
        StringStruct("ProductName", "Serial Link"),
        StringStruct("ProductVersion", "{semver}"),
      ]),
    ]),
    VarFileInfo([VarStruct("Translation", [1033, 1200])]),
  ],
)
"""


def _read_semver() -> str:
    text = VERSION_PY.read_text(encoding="utf-8")
    m = re.search(r'__version__\s*=\s*["\']([^"\']+)["\']', text)
    if not m:
        raise SystemExit(f"Could not parse __version__ in {VERSION_PY}")
    return m.group(1).strip()


def _semver_tuple(semver: str) -> tuple[int, int, int]:
    parts = semver.split(".")
    if len(parts) < 3:
        raise SystemExit(f"Expected semver X.Y.Z, got {semver!r}")
    return int(parts[0]), int(parts[1]), int(parts[2])


def main() -> None:
    semver = _read_semver()
    major, minor, patch = _semver_tuple(semver)
    VERSION_INFO.write_text(
        _TEMPLATE.format(major=major, minor=minor, patch=patch, semver=semver),
        encoding="utf-8",
    )
    print(f"[sync_version_info] {VERSION_INFO.name} -> {semver}")


if __name__ == "__main__":
    main()
